language: java
jdk:
  - openjdk11

# Habilita Travis CI en tu repositorio
branches:
  only:
    - main
    - master

# Indica a Travis que construya el proyecto
script:
  - mvn clean install -DskipTests=false
